<a href="https://colab.research.google.com/github/codemaster-omvardhan/ML-projects/blob/main/PyTorch_TrainingPipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [45]:
from google.colab import files
uploaded = files.upload()

Saving breast-cancer.csv to breast-cancer (1).csv

In [46]:
df = pd.read_csv('breast-cancer.csv')

In [47]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [48]:
df.shape

(569, 32)

In [49]:
df.drop(columns=['id'], inplace=True)

In [50]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [51]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size = 0.2)

In [52]:
scaler = StandardScaler()

In [53]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [54]:
X_train

array([[ 0.09976067,  0.03615362,  0.08161626, ..., -0.28080308,
        -0.67576709, -0.49088461],
       [ 1.08004447, -2.08244761,  1.25622717, ...,  2.28043515,
         2.7787057 ,  1.91618067],
       [-1.3434664 , -0.20502643, -1.33491102, ..., -0.96728627,
        -0.703338  , -0.12495849],
       ...,
       [ 0.03176411, -0.55970297, -0.08089559, ..., -1.22709794,
        -0.69685073, -1.22110567],
       [-1.5446229 , -0.79378949, -1.49865713, ..., -0.14386918,
         0.06216019,  0.98097573],
       [-1.22702228, -0.82925715, -1.2040787 , ..., -0.7442019 ,
        -0.62549073,  0.45845716]])

In [55]:
y_train

448    B
0      M
359    B
83     M
234    B
      ..
266    B
73     M
270    B
114    B
524    B
Name: diagnosis, Length: 455, dtype: object

In [56]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [57]:
y_train

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0])

**Numpy arrays to PyTorch tensors**

In [58]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [59]:
X_train_tensor.shape

torch.Size([455, 30])

In [60]:
y_train_tensor.shape

torch.Size([455])

**Defining the model**

In [61]:
# class MySimpleNN:
#   def __init__(self,X):
#     self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
#     self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

#   def forward(self,X):
#     z = torch.matmul(X, self.weights) + self.bias
#     y_pred = torch.sigmoid(z)
#     return y_pred

#   def loss_function(self, y_pred, y):
#     #Clamp predictions to avoid log(0)
#     epsilon = 1e-7
#     y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

#     #Calculate loss
#     loss = -(y_train_tensor*torch.log(y_pred) + (1-y_train_tensor)*torch.log(1-y_pred)).mean()
#     return loss

In [62]:
import torch.nn as  nn

class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

**Important Parameters**

In [63]:
learning_rate = 0.1
epochs = 25

In [64]:
loss_function = nn.BCELoss()

**Training Pipeline**

In [65]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

#define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# Convert tensors to float32 to match model's default dtype
X_train_tensor = X_train_tensor.float()
y_train_tensor = y_train_tensor.float()

#define loop
for epoch in range(epochs):

  #forward pass
  y_pred = model(X_train_tensor)

  #loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))

  #clear gradients
  # model.linear.weight.grad.zero_()
  # model.linear.bias.grad.zero_()
  optimizer.zero_grad()

  #backward pass
  loss.backward()

  #parameter update
  # with torch.no_grad():
  #   model.linear.weight -= learning_rate * model.linear.weight.grad
  #   model.linear.bias -= learning_rate * model.linear.bias.grad
  optimizer.step()

  #print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.6277137994766235
Epoch: 2, Loss: 0.4858315587043762
Epoch: 3, Loss: 0.4097509980201721
Epoch: 4, Loss: 0.3618148863315582
Epoch: 5, Loss: 0.32833006978034973
Epoch: 6, Loss: 0.3033287227153778
Epoch: 7, Loss: 0.28378021717071533
Epoch: 8, Loss: 0.26797065138816833
Epoch: 9, Loss: 0.25485169887542725
Epoch: 10, Loss: 0.2437429577112198
Epoch: 11, Loss: 0.2341819852590561
Epoch: 12, Loss: 0.22584225237369537
Epoch: 13, Loss: 0.218486025929451
Epoch: 14, Loss: 0.2119356393814087
Epoch: 15, Loss: 0.2060554325580597
Epoch: 16, Loss: 0.2007395625114441
Epoch: 17, Loss: 0.1959044188261032
Epoch: 18, Loss: 0.19148266315460205
Epoch: 19, Loss: 0.18741953372955322
Epoch: 20, Loss: 0.1836698204278946
Epoch: 21, Loss: 0.18019607663154602
Epoch: 22, Loss: 0.17696666717529297
Epoch: 23, Loss: 0.17395487427711487
Epoch: 24, Loss: 0.17113788425922394
Epoch: 25, Loss: 0.1684960275888443

In [66]:
model.linear.weight

Parameter containing:
tensor([[ 0.1145,  0.3293,  0.2446,  0.2015,  0.2483,  0.1106,  0.1177,  0.1039,
         -0.0144,  0.0441,  0.1627, -0.0124,  0.1952,  0.2007, -0.0463,  0.1323,
          0.0395,  0.0884, -0.0950, -0.1963,  0.1846,  0.1011,  0.3930,  0.3985,
          0.1259,  0.0190,  0.2944,  0.3130,  0.3027,  0.0072]],
       requires_grad=True)

In [67]:
model.linear.bias

Parameter containing:
tensor([-0.2129], requires_grad=True)

**Evaluation**

In [68]:
#model evaluation
with torch.no_grad():
  # Convert test tensors to float32 to match model's default dtype
  X_test_tensor = X_test_tensor.float()
  y_test_tensor = y_test_tensor.float()

  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.586334228515625