<a href="https://colab.research.google.com/github/codemaster-omvardhan/ML-projects/blob/main/PyTorch_TrainingPipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
from google.colab import files
uploaded = files.upload()

Saving breast-cancer.csv to breast-cancer.csv

In [3]:
df = pd.read_csv('breast-cancer.csv')

In [4]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [5]:
df.shape

(569, 32)

In [6]:
df.drop(columns=['id'], inplace=True)

In [7]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [8]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size = 0.2)

In [9]:
scaler = StandardScaler()

In [10]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
X_train

array([[ 0.94549852,  4.57085111,  0.88116186, ...,  1.44810602,
        -0.05704226,  0.10357485],
       [ 1.38531783, -0.10028863,  1.29448739, ...,  0.1288588 ,
        -0.07719305, -1.08451002],
       [-0.56245338, -0.34565532, -0.59069031, ..., -0.85093118,
        -1.10824215, -0.57706712],
       ...,
       [ 1.80514534,  0.30330518,  1.76154522, ...,  0.74336665,
         0.55923628, -1.17870601],
       [-0.45963848, -0.29291295, -0.52331826, ..., -1.51164379,
        -1.09816675, -1.70438039],
       [-0.59958098, -1.0817554 , -0.58035718, ..., -0.74732049,
        -0.23504096, -0.01492978]])

In [12]:
y_train

239    M
127    M
96     B
134    M
541    B
      ..
265    M
248    B
533    M
360    B
48     B
Name: diagnosis, Length: 455, dtype: object

In [13]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [14]:
y_train

array([1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0])

**Numpy arrays to PyTorch tensors**

In [15]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [18]:
X_train_tensor.shape

torch.Size([455, 30])

In [19]:
y_train_tensor.shape

torch.Size([455])

**Defining the model**

In [32]:
class MySimpleNN:
  def __init__(self,X):
    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self,X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    #Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    #Calculate loss
    loss = -(y_train_tensor*torch.log(y_pred) + (1-y_train_tensor)*torch.log(1-y_pred)).mean()
    return loss

**Important Parameters**

In [37]:
learning_rate = 0.1
epochs = 25

**Training Pipeline**

In [38]:
#create model
model = MySimpleNN(X_train_tensor)

#define loop
for epoch in range(epochs):
  #forward pass
  y_pred = model.forward(X_train_tensor)
  print(y_pred)

  #loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

  #backward pass
  loss.backward()

  #parameter update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  #zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Streaming output truncated to the last 5000 lines.
        [0.4330],
        [0.9144],
        [0.9612],
        [0.0241],
        [1.0000],
        [0.0131],
        [0.7757],
        [0.8923],
        [0.3338],
        [0.1069],
        [0.0208],
        [0.9701],
        [0.0346],
        [0.0208],
        [0.9979],
        [0.0734],
        [0.0657],
        [0.1432],
        [0.0801],
        [0.0434],
        [0.9980],
        [0.7428],
        [0.7236],
        [0.9804],
        [0.0369],
        [0.0400],
        [0.0434],
        [0.0939],
        [0.9318],
        [0.9835],
        [0.2584],
        [0.9845],
        [0.1774],
        [0.4360],
        [0.9999],
        [0.0246],
        [0.0498],
        [0.9986],
        [0.0187],
        [0.1495],
        [0.9957],
        [0.8658],
        [0.9731],
        [0.1177],
        [0.6451],
        [0.1566],
        [0.9417],
        [0.9915],
        [0.0116],
        [0.9969],
        [0.1743],
        [0.2812],
        [0.7112],
        [0.0800],
        [0.3894],
        [0.9880],
        [0.0769],
        [0.0118],
        [0.0358],
        [0.1375],
        [0.1105],
        [0.9997],
        [0.9922],
        [0.9999],
        [0.6424],
        [0.0222],
        [0.0672],
        [0.3608],
        [0.0256],
        [0.1043],
        [0.0572],
        [0.1115],
        [0.3494],
        [0.6508],
        [0.9342],
        [0.6175],
        [0.9440],
        [0.8889],
        [0.7721],
        [0.9586],
        [0.0144],
        [0.0415],
        [0.2114],
        [0.0654],
        [0.9979],
        [0.0321],
        [0.9861],
        [0.8820],
        [0.7643],
        [0.9352],
        [0.9955],
        [0.7169],
        [0.7861],
        [0.9797],
        [0.9996],
        [0.0073],
        [0.5226],
        [0.9151],
        [0.8442],
        [0.5407],
        [0.0102],
        [0.9962],
        [0.8516],
        [0.0344],
        [0.0609],
        [0.7276],
        [0.9169],
        [0.9903],
        [0.8072],
        [0.2776],
        [0.0917],
        [0.0468],
        [0.8584],
        [0.0760],
        [0.1303],
        [0.1541],
        [0.9261],
        [0.0090],
        [0.7058],
        [0.0293],
        [0.0328],
        [0.5942],
        [0.0724],
        [0.0027],
        [0.4060],
        [0.0552],
        [0.9839],
        [0.0796],
        [0.2377],
        [0.0655],
        [0.3265],
        [0.7446],
        [0.0405],
        [0.0206],
        [0.7441],
        [0.1128],
        [0.1404],
        [0.7184],
        [0.9543],
        [0.0852],
        [0.5651],
        [0.0757],
        [0.0451],
        [0.0666],
        [0.0286],
        [0.1316],
        [0.2859],
        [0.9814],
        [0.0869],
        [0.1285],
        [0.0535],
        [0.1581],
        [0.0382],
        [0.0632],
        [0.9898],
        [0.1166],
        [0.0297],
        [0.6969],
        [0.0121],
        [0.0851],
        [0.9178],
        [0.0892],
        [0.3862],
        [0.9450],
        [0.1014],
        [0.0270],
        [0.5115],
        [0.2876],
        [0.0101],
        [0.9830],
        [0.2157],
        [0.9655],
        [0.3339],
        [0.2846],
        [0.7552],
        [0.1308],
        [0.0757],
        [0.9183],
        [0.7562],
        [0.5314],
        [0.0089],
        [0.0840],
        [0.1982],
        [0.8814],
        [0.9940],
        [0.0341],
        [0.0192],
        [0.1558],
        [0.4446],
        [0.4817],
        [0.0612],
        [0.1099],
        [0.2064],
        [0.0197],
        [0.1405],
        [0.5776],
        [0.0113],
        [0.9884],
        [0.0115],
        [0.0665],
        [0.0281],
        [0.0311],
        [0.0053],
        [0.1057],
        [0.0500],
        [0.5629],
        [0.0050],
        [0.1138],
        [0.1721],
        [1.0000],
        [0.9995],
        [0.6366],
        [0.1293],
        [0.9481],
        [0.0090],
        [0.3507],
        [0.0444],
        [0.2034],
        [0.9875],
        [0.9986],
        [0.0519],
        [0.7184],
        [0.9637],
        [0.9973],
        [0.0352],
        [0.2283],
        [0.3243],
        [0.3745],
        [0.9673],
        [0.9981],
        [0.0063],
        [0.5504],
        [0.7276],
        [0.9273],
        [0.0206],
        [0.2285],
        [0.2147],
        [0.8848],
        [0.0846],
        [0.7244],
        [0.4686],
        [0.6728],
        [0.9670],
        [0.0199],
        [0.9103],
        [0.2740],
        [0.1982],
        [0.0206],
        [0.8380],
        [0.9856],
        [0.6598],
        [0.0721],
        [0.9972],
        [0.0108],
        [0.2669],
        [0.0200],
        [0.0683],
        [0.0106],
        [0.9398],
        [0.2208],
        [0.8771],
        [0.7120],
        [0.3592],
        [0.9670],
        [0.7999],
        [0.4308],
        [0.1258],
        [0.0666],
        [0.4064],
        [0.9618],
        [0.1381],
        [0.1730],
        [0.9591],
        [0.2945],
        [0.4120],
        [0.1788],
        [0.2452],
        [0.5225],
        [0.0983],
        [0.7858],
        [0.5373],
        [0.1547],
        [0.9480],
        [0.0273],
        [0.2414],
        [0.1092],
        [0.9604],
        [0.6058],
        [0.9953],
        [0.8539],
        [0.0416],
        [0.2059],
        [0.4561],
        [0.6159],
        [0.9847],
        [0.0528],
        [0.0573],
        [0.0023],
        [0.9904],
        [0.9987],
        [0.0204],
        [0.6139],
        [0.0924],
        [0.1188],
        [0.6169],
        [0.8009],
        [0.0892],
        [0.1972],
        [0.9404],
        [0.2864],
        [0.9911],
        [0.1492],
        [0.0214],
        [0.0965],
        [0.5663],
        [0.1566],
        [0.9903],
        [0.9936],
        [0.1757],
        [1.0000],
        [0.3935],
        [0.8888],
        [0.0119],
        [0.2740],
        [0.5467],
        [0.1590],
        [0.4784],
        [0.1837],
        [0.9629],
        [0.1872],
        [0.9613],
        [0.3499],
        [0.0155],
        [0.5332],
        [0.9739],
        [0.2816],
        [0.0104],
        [0.6307],
        [0.4756],
        [0.0514],
        [0.1295],
        [0.1441],
        [0.5406],
        [0.6647],
        [1.0000],
        [0.0160],
        [0.1769],
        [0.4603],
        [0.3243],
        [0.9813],
        [0.9999],
        [0.5814],
        [0.0649],
        [0.8323],
        [0.1686],
        [0.2182],
        [0.0438],
        [0.3193],
        [0.2506],
        [0.2413],
        [0.1007],
        [0.1864],
        [0.1761],
        [0.4757],
        [0.1642],
        [0.5796],
        [0.0655],
        [0.3569],
        [0.7040],
        [1.0000],
        [0.2645],
        [0.9967],
        [0.0800],
        [0.6262],
        [0.0728],
        [0.0617],
        [0.2624],
        [0.0808],
        [0.0139],
        [0.9884],
        [0.0132],
        [0.4523],
        [0.3772],
        [0.4794],
        [0.0575],
        [0.0332],
        [0.9603],
        [0.0288],
        [0.9899],
        [0.0750],
        [0.1632],
        [0.2445],
        [0.0047],
        [0.1298],
        [0.4072],
        [0.7494],
        [0.3418],
        [0.6884],
        [0.1011],
        [0.5213],
        [0.9987],
        [0.7164],
        [0.9252],
        [0.0637],
        [0.4051],
        [0.0290],
        [0.9946],
        [0.6701],
        [0.5694],
        [0.1777],
        [0.0257],
        [0.9992],
        [0.0205],
        [0.9703],
        [0.9901],
        [0.2913],
        [0.9377],
        [0.9308],
        [0.5520],
        [0.9893],
        [0.9616],
        [0.1156],
        [0.3851],
        [0.9952],
        [0.4057],
        [0.9628],
        [0.0174],
        [0.0602]], dtype=torch.float64, grad_fn=<SigmoidBackward0>)
Epoch: 15, Loss: 1.4824274651583857
Epoch: 15, Loss: 1.4824274651583857
tensor([[0.8852],
        [0.6845],
        [0.0576],
        [0.7170],
        [0.8230],
        [0.1227],
        [0.9295],
        [0.1146],
        [0.9579],
        [0.1535],
        [0.1109],
        [0.7610],
        [0.0362],
        [1.0000],
        [0.6471],
        [0.5167],
        [0.9049],
        [0.4395],
        [0.1262],
        [0.3062],
        [0.0995],
        [0.2288],
        [0.1919],
        [0.9706],
        [0.1941],
        [0.9481],
        [0.9524],
        [0.3475],
        [0.9246],
        [0.9385],
        [0.0347],
        [1.0000],
        [0.0184],
        [0.8201],
        [0.8496],
        [0.2994],
        [0.1647],
        [0.0317],
        [0.9499],
        [0.0441],
        [0.0299],
        [0.9968],
        [0.0771],
        [0.0836],
        [0.1687],
        [0.1193],
        [0.0621],
        [0.9968],
        [0.6899],
        [0.6944],
        [0.9666],
        [0.0512],
        [0.0588],
        [0.0569],
        [0.1295],
        [0.9326],
        [0.9735],
        [0.3049],
        [0.9683],
        [0.2319],
        [0.4466],
        [0.9999],
        [0.0344],
        [0.0699],
        [0.9968],
        [0.0271],
        [0.1653],
        [0.9913],
        [0.8611],
        [0.9635],
        [0.1531],
        [0.6127],
        [0.1923],
        [0.9347],
        [0.9858],
        [0.0170],
        [0.9929],
        [0.1949],
        [0.2894],
        [0.6694],
        [0.1103],
        [0.3448],
        [0.9792],
        [0.0799],
        [0.0182],
        [0.0498],
        [0.1640],
        [0.1169],
        [0.9990],
        [0.9917],
        [0.9998],
        [0.6563],
        [0.0286],
        [0.0831],
        [0.4022],
        [0.0414],
        [0.1499],
        [0.0673],
        [0.1301],
        [0.3468],
        [0.6244],
        [0.8971],
        [0.5506],
        [0.9189],
        [0.8466],
        [0.7271],
        [0.9303],
        [0.0214],
        [0.0455],
        [0.2506],
        [0.0769],
        [0.9950],
        [0.0444],
        [0.9788],
        [0.8752],
        [0.7174],
        [0.9167],
        [0.9911],
        [0.6419],
        [0.7320],
        [0.9637],
        [0.9988],
        [0.0132],
        [0.5332],
        [0.8819],
        [0.7858],
        [0.5857],
        [0.0172],
        [0.9929],
        [0.7999],
        [0.0469],
        [0.0755],
        [0.6858],
        [0.8651],
        [0.9834],
        [0.8323],
        [0.2774],
        [0.1331],
        [0.0606],
        [0.8110],
        [0.0932],
        [0.1754],
        [0.1783],
        [0.8996],
        [0.0159],
        [0.6740],
        [0.0360],
        [0.0566],
        [0.5605],
        [0.0809],
        [0.0049],
        [0.3688],
        [0.0835],
        [0.9731],
        [0.1062],
        [0.2840],
        [0.0943],
        [0.3043],
        [0.7678],
        [0.0549],
        [0.0300],
        [0.8068],
        [0.1315],
        [0.1547],
        [0.6488],
        [0.9280],
        [0.1076],
        [0.5744],
        [0.0886],
        [0.0619],
        [0.0932],
        [0.0404],
        [0.1458],
        [0.2683],
        [0.9726],
        [0.1018],
        [0.1780],
        [0.0768],
        [0.1824],
        [0.0442],
        [0.0744],
        [0.9830],
        [0.1273],
        [0.0362],
        [0.6873],
        [0.0178],
        [0.1209],
        [0.8910],
        [0.1199],
        [0.4779],
        [0.9247],
        [0.1346],
        [0.0359],
        [0.4646],
        [0.3520],
        [0.0155],
        [0.9676],
        [0.2415],
        [0.9473],
        [0.3860],
        [0.2832],
        [0.6946],
        [0.1742],
        [0.0997],
        [0.9280],
        [0.6970],
        [0.5078],
        [0.0134],
        [0.1167],
        [0.2220],
        [0.8526],
        [0.9911],
        [0.0531],
        [0.0291],
        [0.2323],
        [0.4508],
        [0.4045],
        [0.0828],
        [0.1333],
        [0.2426],
        [0.0274],
        [0.1768],
        [0.5540],
        [0.0182],
        [0.9765],
        [0.0177],
        [0.0902],
        [0.0377],
        [0.0488],
        [0.0091],
        [0.1082],
        [0.0665],
        [0.5082],
        [0.0086],
        [0.1636],
        [0.1772],
        [1.0000],
        [0.9987],
        [0.6270],
        [0.1510],
        [0.9218],
        [0.0122],
        [0.3954],
        [0.0536],
        [0.2349],
        [0.9805],
        [0.9970],
        [0.0673],
        [0.7543],
        [0.9458],
        [0.9924],
        [0.0420],
        [0.2379],
        [0.3507],
        [0.3940],
        [0.9474],
        [0.9963],
        [0.0105],
        [0.5195],
        [0.6710],
        [0.8820],
        [0.0271],
        [0.2616],
        [0.2673],
        [0.8759],
        [0.1035],
        [0.7025],
        [0.4346],
        [0.6253],
        [0.9536],
        [0.0289],
        [0.9198],
        [0.3068],
        [0.2192],
        [0.0338],
        [0.8570],
        [0.9767],
        [0.6171],
        [0.1050],
        [0.9937],
        [0.0146],
        [0.3202],
        [0.0327],
        [0.1057],
        [0.0174],
        [0.9040],
        [0.2467],
        [0.8204],
        [0.7279],
        [0.4205],
        [0.9467],
        [0.8126],
        [0.4819],
        [0.1572],
        [0.0844],
        [0.4583],
        [0.9378],
        [0.1512],
        [0.2561],
        [0.9462],
        [0.3164],
        [0.4204],
        [0.1713],
        [0.2721],
        [0.6022],
        [0.1363],
        [0.7643],
        [0.5352],
        [0.1595],
        [0.9237],
        [0.0372],
        [0.2819],
        [0.1155],
        [0.9271],
        [0.5910],
        [0.9900],
        [0.8524],
        [0.0557],
        [0.2058],
        [0.4194],
        [0.6958],
        [0.9608],
        [0.0784],
        [0.0717],
        [0.0041],
        [0.9814],
        [0.9959],
        [0.0303],
        [0.5780],
        [0.1163],
        [0.1571],
        [0.6427],
        [0.7317],
        [0.1164],
        [0.2057],
        [0.9217],
        [0.3495],
        [0.9782],
        [0.2089],
        [0.0319],
        [0.1130],
        [0.5776],
        [0.1842],
        [0.9834],
        [0.9869],
        [0.1968],
        [1.0000],
        [0.4523],
        [0.8461],
        [0.0204],
        [0.3412],
        [0.5777],
        [0.1995],
        [0.5530],
        [0.2160],
        [0.9495],
        [0.2431],
        [0.9287],
        [0.3993],
        [0.0238],
        [0.5447],
        [0.9635],
        [0.3101],
        [0.0168],
        [0.6673],
        [0.4832],
        [0.0700],
        [0.1603],
        [0.2305],
        [0.4652],
        [0.6150],
        [1.0000],
        [0.0235],
        [0.1861],
        [0.4805],
        [0.3168],
        [0.9679],
        [0.9997],
        [0.6005],
        [0.0883],
        [0.7748],
        [0.2016],
        [0.2561],
        [0.0505],
        [0.3177],
        [0.2837],
        [0.2606],
        [0.1359],
        [0.1934],
        [0.1834],
        [0.4267],
        [0.1636],
        [0.5976],
        [0.0903],
        [0.3892],
        [0.7118],
        [1.0000],
        [0.3088],
        [0.9938],
        [0.1064],
        [0.5687],
        [0.0946],
        [0.0926],
        [0.2861],
        [0.0840],
        [0.0184],
        [0.9838],
        [0.0200],
        [0.5059],
        [0.3608],
        [0.5071],
        [0.0829],
        [0.0462],
        [0.9430],
        [0.0498],
        [0.9795],
        [0.1041],
        [0.1723],
        [0.2825],
        [0.0082],
        [0.1915],
        [0.4537],
        [0.7134],
        [0.3859],
        [0.7483],
        [0.1184],
        [0.4389],
        [0.9964],
        [0.6249],
        [0.8971],
        [0.0826],
        [0.4944],
        [0.0376],
        [0.9903],
        [0.7177],
        [0.5298],
        [0.2268],
        [0.0341],
        [0.9982],
        [0.0277],
        [0.9574],
        [0.9773],
        [0.3169],
        [0.9096],
        [0.9112],
        [0.5951],
        [0.9810],
        [0.9492],
        [0.1413],
        [0.3511],
        [0.9906],
        [0.4618],
        [0.9443],
        [0.0300],
        [0.0758]], dtype=torch.float64, grad_fn=<SigmoidBackward0>)
Epoch: 16, Loss: 1.3553115431694516
Epoch: 16, Loss: 1.3553115431694516
tensor([[0.8431],
        [0.6514],
        [0.0728],
        [0.6770],
        [0.7975],
        [0.1723],
        [0.8933],
        [0.1312],
        [0.9324],
        [0.1869],
        [0.1434],
        [0.6965],
        [0.0501],
        [1.0000],
        [0.6668],
        [0.5384],
        [0.8895],
        [0.4947],
        [0.1513],
        [0.3432],
        [0.1369],
        [0.2128],
        [0.2190],
        [0.9515],
        [0.2326],
        [0.9154],
        [0.9187],
        [0.2767],
        [0.9323],
        [0.9064],
        [0.0486],
        [0.9999],
        [0.0254],
        [0.8537],
        [0.7979],
        [0.2707],
        [0.2379],
        [0.0470],
        [0.9196],
        [0.0556],
        [0.0420],
        [0.9953],
        [0.0810],
        [0.1040],
        [0.1961],
        [0.1696],
        [0.0862],
        [0.9949],
        [0.6354],
        [0.6656],
        [0.9451],
        [0.0696],
        [0.0835],
        [0.0732],
        [0.1728],
        [0.9324],
        [0.9587],
        [0.3513],
        [0.9393],
        [0.2917],
        [0.4559],
        [0.9998],
        [0.0472],
        [0.0950],
        [0.9930],
        [0.0384],
        [0.1809],
        [0.9829],
        [0.8557],
        [0.9513],
        [0.1941],
        [0.5817],
        [0.2312],
        [0.9269],
        [0.9769],
        [0.0244],
        [0.9847],
        [0.2164],
        [0.2970],
        [0.6269],
        [0.1474],
        [0.3073],
        [0.9651],
        [0.0838],
        [0.0273],
        [0.0676],
        [0.1927],
        [0.1237],
        [0.9973],
        [0.9912],
        [0.9995],
        [0.6676],
        [0.0364],
        [0.1011],
        [0.4412],
        [0.0644],
        [0.2057],
        [0.0786],
        [0.1499],
        [0.3451],
        [0.5985],
        [0.8475],
        [0.4862],
        [0.8861],
        [0.7967],
        [0.6813],
        [0.8888],
        [0.0311],
        [0.0499],
        [0.2912],
        [0.0896],
        [0.9887],
        [0.0601],
        [0.9684],
        [0.8681],
        [0.6683],
        [0.8953],
        [0.9830],
        [0.5657],
        [0.6739],
        [0.9383],
        [0.9969],
        [0.0231],
        [0.5416],
        [0.8410],
        [0.7192],
        [0.6238],
        [0.0280],
        [0.9873],
        [0.7404],
        [0.0626],
        [0.0923],
        [0.6435],
        [0.7950],
        [0.9726],
        [0.8515],
        [0.2773],
        [0.1849],
        [0.0768],
        [0.7559],
        [0.1123],
        [0.2277],
        [0.2038],
        [0.8674],
        [0.0271],
        [0.6431],
        [0.0439],
        [0.0923],
        [0.5285],
        [0.0901],
        [0.0086],
        [0.3360],
        [0.1213],
        [0.9568],
        [0.1381],
        [0.3316],
        [0.1310],
        [0.2852],
        [0.7865],
        [0.0729],
        [0.0427],
        [0.8525],
        [0.1514],
        [0.1695],
        [0.5786],
        [0.8912],
        [0.1333],
        [0.5813],
        [0.1029],
        [0.0830],
        [0.1265],
        [0.0559],
        [0.1608],
        [0.2530],
        [0.9607],
        [0.1180],
        [0.2366],
        [0.1068],
        [0.2078],
        [0.0508],
        [0.0868],
        [0.9725],
        [0.1387],
        [0.0436],
        [0.6778],
        [0.0257],
        [0.1650],
        [0.8584],
        [0.1560],
        [0.5636],
        [0.8996],
        [0.1738],
        [0.0470],
        [0.4225],
        [0.4168],
        [0.0232],
        [0.9415],
        [0.2676],
        [0.9225],
        [0.4366],
        [0.2826],
        [0.6281],
        [0.2237],
        [0.1280],
        [0.9351],
        [0.6358],
        [0.4839],
        [0.0197],
        [0.1567],
        [0.2464],
        [0.8202],

In [39]:
model.weights

tensor([[ 0.0429],
        [ 0.1699],
        [-0.2634],
        [-0.0718],
        [-0.3556],
        [ 0.2262],
        [ 0.2904],
        [-0.5390],
        [ 0.2235],
        [-0.0940],
        [ 0.2355],
        [ 0.0762],
        [ 0.0399],
        [ 0.2956],
        [ 0.7254],
        [ 0.3262],
        [ 0.0777],
        [-0.1778],
        [ 0.1720],
        [-0.3187],
        [ 0.2679],
        [ 0.1012],
        [-0.2169],
        [-0.0708],
        [ 0.1177],
        [-0.2775],
        [ 0.1402],
        [ 0.0579],
        [ 0.2515],
        [-0.0631]], dtype=torch.float64, requires_grad=True)

In [40]:
model.bias

tensor([-0.1399], dtype=torch.float64, requires_grad=True)

**Evaluation**

In [46]:
#model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5846414566040039